export const nigeriaLocations = {
  Abia: ['Aba', 'Arochukwu', 'Ohafia', 'Umuahia'],
  Adamawa: ['Ganye', 'Gombi', 'Mubi', 'Numan', 'Yola'],
  Anambra: ['Awka', 'Nnewi', 'Onitsha', 'Ekwulobia'],
  Bauchi: ['Bauchi', 'Azare', 'Jamaare', 'Katagum'],
  Bayelsa: ['Brass', 'Ogbia', 'Sagbama', 'Yenagoa'],
  Benue: ['Gboko', 'Makurdi', 'Otukpo', 'Katsina-Ala'],
  Borno: ['Bama', 'Biu', 'Maiduguri', 'Monguno'],
  'Cross River': ['Calabar', 'Ikom', 'Obudu', 'Ogoja'],
  Delta: ['Asaba', 'Igbudu', 'Sapele', 'Ughelli', 'Warri'],
  Ebonyi: ['Abakaliki', 'Afikpo', 'Onueke'],
  Edo: ['Auchi', 'Benin City', 'Ekpoma', 'Uromi'],
  Ekiti: ['Ado-Ekiti', 'Ikere', 'Ilawe', 'Oye'],
  Enugu: ['Enugu', 'Nsukka', 'Oji River', 'Udi'],
  Gombe: ['Billiri', 'Gombe', 'Kaltungo', 'Kumo'],
  Imo: ['Ihiala', 'Okigwe', 'Owerri', 'Orlu'],
  Jigawa: ['Dutse', 'Gumel', 'Hadejia', 'Kazaure'],
  Kaduna: ['Birnin Gwari', 'Kaduna', 'Kafanchan', 'Zaria'],
  Kano: ['Kano', 'Bichi', 'Dambatta', 'Wudil'],
  Katsina: ['Daura', 'Funtua', 'Katsina', 'Malumfashi'],
  Kebbi: ['Argungu', 'Birnin Kebbi', 'Jega', 'Yauri'],
  Kogi: ['Idah', 'Kabba', 'Lokoja', 'Okene'],
  Kwara: ['Ilorin', 'Jebba', 'Offa', 'Omu-Aran'],
  Lagos: ['Badagry', 'Epe', 'Ikeja', 'Ikorodu', 'Lagos Island', 'Lekki', 'Surulere'],
  Nasarawa: ['Akwanga', 'Keffi', 'Lafia', 'Nasarawa'],
  Niger: ['Bida', 'Kontagora', 'Minna', 'Suleja'],
  Ogun: ['Abeokuta', 'Ijebu-Ode', 'Sagamu', 'Ota'],
  Ondo: ['Akure', 'Ikare', 'Ondo', 'Owo'],
  Osun: ['Ede', 'Ife', 'Ilesa', 'Osogbo'],
  Oyo: ['Ibadan', 'Iseyin', 'Ogbomosho', 'Oyo'],
  Plateau: ['Barkin Ladi', 'Jos', 'Pankshin', 'Shendam'],
  Rivers: ['Bonny', 'Obio-Akpor', 'Port Harcourt', 'Yenagoa'],
  Sokoto: ['Gwadabawa', 'Sokoto', 'Tambuwal', 'Wurno'],
  Taraba: ['Jalingo', 'Serti', 'Takum', 'Wukari'],
  Yobe: ['Damaturu', 'Gashua', 'Nguru', 'Potiskum'],
  Zamfara: ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Tsafe'],
  'Federal Capital Territory': ['Abuja', 'Gwagwalada', 'Kuje', 'Kwali', 'Bwari'],
};

export const nigeriaStates = Object.keys(nigeriaLocations);
